# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on ubuntu x86 platforms

on:
  push:
    # branches: [ "main" ]
    tags:
     - 'v*'

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: get_tag
      run: echo "tag=$(git tag)" >> $GITHUB_ENV

    - name: Enable i386 architecture
      run: sudo dpkg --add-architecture i386

    - name: Update package list
      run: sudo apt-get update

    - name: Install packages
      run: sudo apt-get install -y gcc-multilib g++-multilib liblzo2-dev liblzo2-dev:i386 liblz4-dev liblz4-dev:i386 libzstd-dev libzstd-dev:i386 libelf-dev libelf-dev:i386 pkg-config

    - name: Build
      run: |
        bash build.sh
        tar -czvf crash-plugins_${{ env.tag }}_x86.tar.gz output/arm64/plugins.so \
                        output/arm/plugins.so

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: crash-plugins_${{ env.tag }}_x86.tar.gz
        path: crash-plugins_${{ env.tag }}_x86.tar.gz

  release:
     needs: build
     runs-on: ubuntu-22.04

     steps:
      - name: checkout branch
        uses: actions/checkout@v4

      - name: get_tag
        run: echo "plugin_tag=$(git tag)" >> $GITHUB_ENV

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
            name: crash-plugins_${{ env.plugin_tag }}_x86.tar.gz

      - name: Release the Crash-plugins
        id: release-crash
        uses: actions/create-release@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            tag_name: ${{ env.plugin_tag }}
            release_name: crash-plugins-${{ env.plugin_tag }}
            files: |
              crash-plugins_${{ env.plugin_tag }}_x86.tar.gz

      - name: Upload Release Asset
        id: upload
        uses: actions/upload-release-asset@latest
        env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
              upload_url: ${{ steps.release-crash.outputs.upload_url }}
              asset_path: crash-plugins_${{ env.plugin_tag }}_x86.tar.gz
              asset_name: crash-plugins_${{ env.plugin_tag }}_x86.tar.gz
              asset_content_type: application/gzip #zip